#ifndef NOTCH_MOCK_MATRIX_H
#define NOTCH_MOCK_MATRIX_H

#include <string>
#include <vector>

#include "comfy_extension_client/client_interface.h"

#include "case_logger.h"

namespace notch_mock
{

// Minimal WebSocket probe used by the Layer 1 handshake case. It is a
// superset of the interface's IWebSocketTransport (which only sends) so the
// orchestration can connect, send the feature-flags message, and drain received
// frames for evidence without depending on the concrete transport library.
class IWebSocketProbe
{
public:
    virtual ~IWebSocketProbe() {}
    virtual bool Connect(int timeoutMs, std::string& error) = 0;
    virtual bool SendText(const std::string& message, std::string& error) = 0;
    virtual std::vector<std::string> DrainReceived() = 0;
    virtual void Close() = 0;
};

class ICudaShareReader
{
public:
    virtual ~ICudaShareReader() {}
    // Whether this environment has a usable CUDA driver + device (cuInit + a
    // device present). No device -> skip (cuda_unavailable). CUDA delivery has a
    // second skip gate, cuda_ipc_unsupported: a verified-valid share whose
    // handle a WSL-marked runner cannot import. With a device present on a normal
    // runner, a failed import is a real failure (e.g. a wrong handle), not a
    // skip. error carries the driver reason when unavailable.
    virtual bool CudaAvailable(std::string& error) = 0;
    virtual bool ReadShare(
        const ComfyExtensionClientProtocol::CudaShareStatus& share,
        std::vector<uint8_t>& bytes,
        std::string& error) = 0;
};

// Which conformance phase to run. Negotiation is Layer 1 (discovery +
// transport selection + readiness decision, no execution). Delivery phases run
// real NotchSingleInput -> NotchOutputNode round trips and validate delivery
// evidence for the relevant topology.
enum class Phase
{
    Negotiation,
    DeliveryLocal,
    DeliveryRemote,
};

enum class VerificationClass
{
    ByteExact,     // delivered bytes == source bytes (file_path, file_3d)
    Structural,    // canonical-JSON(delivered) == canonical-JSON(expected) (load3d_camera)
    DecodedImage,  // stb_image dims+channels+sample hash (image over disk/http)
    Integrity,     // exists + non-empty (+ server hash if present) (audio, video, mesh GLB)
    CudaRaw,       // raw float32 RGBA buffer vs expected pattern (image over cuda)
};

struct VerifyResult
{
    bool ok = false;
    std::string detail;   // compact JSON fragment describing the comparison
    std::string error;    // a stable error code on failure, e.g. "output_hash_mismatch"
};

struct MatrixOptions
{
    Phase phase = Phase::Negotiation;
    std::string baseUrl;           // http://127.0.0.1:8188
    std::string outputRoot;        // artifact directory root
    std::string clientId;          // must match the /ws clientId for event routing
    std::string parseWorkflowJson; // optional API workflow body for /notch/parse
    // Deployment-readiness gate fixtures (POST /notch/get-required-files): a
    // workflow whose referenced files all exist on the server, and one that
    // references a missing file. Empty fixtures skip the gate.
    std::string requiredFilesReadyJson;
    std::string requiredFilesMissingJson;
    // Delivery fixtures. assetRoot normally points at the caller checkout's
    // tests/assets/round_trip directory. sourceFilePath is copied byte-for-byte
    // through the file_path workflow for disk/http hash checks. CUDA uses a
    // deterministic raw-buffer image generated by the mock client.
    std::string assetRoot;
    std::string sourceFilePath;
    std::string localOutputPath;
    // Named-route disk handoff used by the remote delivery topology. The server
    // advertises namedRouteId in /features; the client maps the same id to its
    // own local root and joins the ready event's relative_path under it.
    std::string namedRouteId;
    std::string namedRouteClientRoot;
    std::string namedRouteRelativeDirectory;
    std::string serverLogPath;
    int wsTimeoutMs = 5000;        // handshake budget
    int executeTimeoutMs = 90000;  // budget to wait for a terminal execution event
};

struct MatrixSummary
{
    int passed = 0;
    int failed = 0;
    int skipped = 0;
    int errored = 0;
    // Set when shared setup itself failed; the matrix aborts before cases run.
    std::string setupFailureCode;

    bool Ok() const { return failed == 0 && errored == 0 && setupFailureCode.empty(); }
};

// Run the conformance suite for the selected phase. Negotiation runs discovery
// (live /features and optional /notch/parse), the readiness decision, the pure
// transport-selection matrix, and a WebSocket handshake check. Delivery phases
// execute real workflows, collect per-case WS/HTTP/diagnostic/log evidence, and
// verify output integrity. Diagnostic-first: every runnable case is executed;
// only a shared-setup failure short-circuits.
// Writes conformance-result.json under options.outputRoot.
MatrixSummary RunConformance(
    ComfyExtensionClientProtocol::IHttpTransport& http,
    IWebSocketProbe& ws,
    const MatrixOptions& options,
    CaseLogger& logger,
    ICudaShareReader* cudaReader = nullptr);

} // namespace notch_mock

#endif
